#include "stdafx.h"
#include "Settings.h"
#include "..\Minecraft.World\StringHelpers.h"

#include <fstream>
#include <sstream>
#include <algorithm>

// Helper function to trim whitespace
static wstring trimWS(const wstring& str)
{
	size_t start = str.find_first_not_of(L" \t\r\n");
	if (start == wstring::npos)
		return L"";
	size_t end = str.find_last_not_of(L" \t\r\n");
	return str.substr(start, end - start + 1);
}

// Helper function to convert wide string to narrow string for file operations
static string wstringToNarrow(const wstring& wstr)
{
	if (wstr.empty())
		return "";
	int size = WideCharToMultiByte(CP_UTF8, 0, wstr.c_str(), -1, nullptr, 0, nullptr, nullptr);
	if (size <= 0)
		return "";
	string result(size - 1, '\0');
	WideCharToMultiByte(CP_UTF8, 0, wstr.c_str(), -1, &result[0], size, nullptr, nullptr);
	return result;
}

// Helper function to convert narrow string to wide string
static wstring narrowToWstring(const string& str)
{
	if (str.empty())
		return L"";
	int size = MultiByteToWideChar(CP_UTF8, 0, str.c_str(), -1, nullptr, 0);
	if (size <= 0)
		return L"";
	wstring result(size - 1, L'\0');
	MultiByteToWideChar(CP_UTF8, 0, str.c_str(), -1, &result[0], size);
	return result;
}

Settings::Settings(File *file)
{
	// Load properties from file if it exists
	if (file != nullptr)
	{
		wstring path = file->getPath();
		string narrowPath = wstringToNarrow(path);

		ifstream inFile(narrowPath);
		if (inFile.is_open())
		{
			string line;
			while (getline(inFile, line))
			{
				// Skip empty lines and comments
				if (line.empty() || line[0] == '#' || line[0] == '!')
					continue;

				// Find the '=' separator
				size_t pos = line.find('=');
				if (pos == string::npos)
				{
					// Also try ':'
					pos = line.find(':');
					if (pos == string::npos)
						continue;
				}

				// Extract key and value
				string key = line.substr(0, pos);
				string value = line.substr(pos + 1);

				// Trim whitespace
				wstring wkey = trimWS(narrowToWstring(key));
				wstring wvalue = trimWS(narrowToWstring(value));

				if (!wkey.empty())
				{
					properties[wkey] = wvalue;
				}
			}
			inFile.close();
		}
	}
}

void Settings::generateNewProperties()
{
	// Generate default properties
	properties[L"level-name"] = L"world";
	properties[L"server-port"] = L"25565";
	properties[L"gamemode"] = L"0";
	properties[L"spawn-monsters"] = L"true";
	properties[L"spawn-animals"] = L"true";
	properties[L"spawn-npcs"] = L"true";
	properties[L"pvp"] = L"true";
	properties[L"allow-nether"] = L"true";
	properties[L"max-build-height"] = L"256";
	properties[L"level-seed"] = L"";
	properties[L"level-type"] = L"default";
}

void Settings::saveProperties()
{
	// Save to server.properties file
	ofstream outFile("server.properties");
	if (outFile.is_open())
	{
		outFile << "# Minecraft Server Properties" << endl;
		outFile << "# Generated by MinecraftConsoles" << endl;
		outFile << endl;

		for (const auto& pair : properties)
		{
			string key = wstringToNarrow(pair.first);
			string value = wstringToNarrow(pair.second);
			outFile << key << "=" << value << endl;
		}
		outFile.close();
	}
}

wstring Settings::getString(const wstring& key, const wstring& defaultValue)
{
	if(properties.find(key) == properties.end())
	{
		properties[key] = defaultValue;
		saveProperties();
	}
	return properties[key];
}

int Settings::getInt(const wstring& key, int defaultValue)
{
	if(properties.find(key) == properties.end())
	{
		properties[key] = _toString<int>(defaultValue);
		saveProperties();
	}
	return _fromString<int>(properties[key]);
}

bool Settings::getBoolean(const wstring& key, bool defaultValue)
{
	if(properties.find(key) == properties.end())
	{
		properties[key] = _toString<bool>(defaultValue);
		saveProperties();
	}
	MemSect(35);
	bool retval = _fromString<bool>(properties[key]);
	MemSect(0);
	return retval;
}

void Settings::setBooleanAndSave(const wstring& key, bool value)
{
	properties[key] = _toString<bool>(value);
	saveProperties();
}